#!/Users/mikewadhera/.rvm/rubies/ree-1.8.7-2011.03/bin/ruby

require 'rubygems'
require 'json'

def emit(message)
  STDOUT.puts(message.to_json)
  STDOUT.flush
end

STDIN.each_line do |json|

  message = JSON.parse(json)

  message['sentence'].split(/\s+/).each do |word|
    emit(:word => word)
  end

end