#!/Users/mikewadhera/.rvm/rubies/ree-1.8.7-2011.03/bin/ruby

require 'rubygems'
require 'json'

def emit(message)
  STDOUT.puts(message.to_json)
  STDOUT.flush
end

Sentences = [
  "The quick brown fox jumped over the lazy dog",
  "Involver is the web's most trusted Social Marketing Platform",
  "I like web sites"
]

loop do
  Sentences.each do |sentence|
    emit(:sentence => sentence)
    sleep 1
  end
end