#!/Users/mikewadhera/.rvm/rubies/ree-1.8.7-2011.03/bin/ruby

require 'rubygems'
require 'json'

def emit(message)
  STDOUT.puts(message.to_json)
  STDOUT.flush
end

word_counts = {}

STDIN.each_line do |json|

  message = JSON.parse(json)

  word = message['word']
  word_counts[word] = (word_counts[word] || 0) + 1

  emit(:word => word, :count => word_counts[word])

end